# Generated by Django 5.2.8 on 2025-12-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usuario_senha_alter_usuario_matricula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
