# Generated by Django 5.2.8 on 2025-12-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usuario_senha_alter_usuario_matricula_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['matricula']},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
    ]
