# Generated by Django 5.2.8 on 2025-12-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usuario_options_remove_usuario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=models.CharField(blank=True, editable=False, max_length=10, unique=True), max_length=50),
        ),
    ]
