# Generated by Django 5.2.8 on 2025-12-02 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('usuario_criador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
                ('materia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assunto', to='main.materia')),
            ],
            options={
                'ordering': ['materia_id', 'titulo'],
            },
        ),
    ]
