# Generated by Django 5.2.8 on 2025-12-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vestibular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vestibular',
            old_name='link',
            new_name='link_gabarito',
        ),
        migrations.AddField(
            model_name='vestibular',
            name='link_prova',
            field=models.CharField(default='exit', max_length=500),
            preserve_default=False,
        ),
    ]
