# Generated by Django 5.2.8 on 2025-12-03 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('main', '0002_materia_assunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assunto',
            name='usuario_criador_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
